import type { AgentScanDecision, AgentThreatFinding } from '../types/agentTypes'

type Props = {
  decision: AgentScanDecision
  onClose: () => void
}

/**
 * Plain-language explanations for the rule-based detector's category names
 * (`app/core/security_constants.py`). A non-technical user should be able to
 * read these without knowing what "jailbreak_attempt" means.
 */
const PATTERN_EXPLANATIONS: Record<string, string> = {
  override_instructions: 'Tries to make the AI forget or ignore its previous instructions.',
  jailbreak_attempt: "Tries to trick the AI into ignoring its safety rules.",
  hidden_instruction: 'Gives the AI a secret command meant to be hidden from you.',
  system_prompt_reveal: "Tries to get the AI to reveal its confidential setup instructions.",
  data_exfiltration: 'Tries to make the AI send your data somewhere it should not go.',
}

/** Where on the page a finding was found, in wording a non-developer can follow. */
const SOURCE_LABELS: Record<string, string> = {
  visible_text: 'Text visible on the page',
  hidden_text: 'Text hidden from view',
  html_comments: 'Hidden HTML comments',
  meta_tags: 'Page metadata',
  input_values: 'Form/input fields',
  aria_text: 'Accessibility text (read by screen readers, not shown visually)',
  iframe_content: 'Content inside an embedded frame',
  shadow_dom_content: 'Content inside shadow DOM (invisible to normal page inspection)',
  inline_javascript: 'Inline script code',
  external_javascript: 'External script code',
  css_content: 'CSS stylesheet content',
  css_generated_content: 'Text generated by CSS (invisible in the page source)',
  network_responses: 'Data loaded from the network',
  websocket_messages: 'Live WebSocket messages',
  service_worker_activity: 'Background service-worker activity',
}

function friendlySource(source: string): string {
  return SOURCE_LABELS[source] ?? source.replaceAll('_', ' ')
}

function friendlyPattern(pattern: string): string {
  return PATTERN_EXPLANATIONS[pattern] ?? 'Matches a known prompt-injection pattern.'
}

function FindingCard({ finding }: { finding: AgentThreatFinding }) {
  return (
    <article className="webpage-scan-chunk">
      <div className="webpage-scan-chunk__header">
        <span>{friendlySource(finding.source)}</span>
        <strong>{Math.round(finding.confidence * 100)}%</strong>
      </div>
      {finding.excerpt ? (
        <p className="webpage-scan-chunk__excerpt">&ldquo;{finding.excerpt}&rdquo;</p>
      ) : null}
      {finding.matched_evidence.length > 0 ? (
        <p className="webpage-scan-chunk__evidence">
          Suspicious text found: {finding.matched_evidence.map((term) => `"${term}"`).join(', ')}
        </p>
      ) : null}
      {finding.matched_patterns.length > 0 ? (
        <div className="webpage-scan-chunk-explanations">
          {finding.matched_patterns.map((pattern) => (
            <p key={pattern} className="webpage-scan-chunk__evidence">
              {friendlyPattern(pattern)}
            </p>
          ))}
        </div>
      ) : null}
      {finding.matched_patterns.length > 0 ? (
        <div className="feature-tags">
          {finding.matched_patterns.map((pattern) => (
            <span className="feature-tag feature-tag--danger" key={pattern}>{pattern.replaceAll('_', ' ')}</span>
          ))}
        </div>
      ) : null}
    </article>
  )
}

export function AgentThreatDetailsModal({ decision, onClose }: Props) {
  return (
    <>
      <div className="analysis-drawer-overlay analysis-drawer-overlay--open" onClick={onClose} />
      <section
        className="analysis-drawer webpage-analysis-drawer analysis-drawer--open"
        aria-label="Threat details"
        aria-modal="true"
        role="dialog"
      >
        <header className="drawer-header">
          <div>
            <h3>What we found</h3>
            <p className="webpage-scan-subtitle">Why the agent was stopped on this page</p>
          </div>
          <button className="drawer-close-btn" type="button" onClick={onClose} aria-label="Close threat details">✕</button>
        </header>

        <div className="drawer-content">
          <div className="drawer-decision drawer-decision--blocked">
            <div className="drawer-decision-label">
              <div>
                <div>Hidden instructions detected on this page</div>
                <div className="webpage-decision-copy">{decision.summary_reason}</div>
              </div>
            </div>
            <div className="drawer-decision-meta"><strong>{Math.round(decision.confidence * 100)}%</strong>confidence</div>
          </div>

          <div className="webpage-credential-notice webpage-credential-notice--blocked">
            <div>
              <strong>Why this matters</strong>
              <p>
                This page contains text that is written to instruct an AI assistant rather than to inform a
                human reader — for example, text that is invisible on screen but still readable by the agent.
                Letting the agent continue could cause it to follow instructions the website's owner planted,
                instead of your instructions.
              </p>
            </div>
          </div>

          <section className="drawer-section">
            <div className="drawer-section-header">Where it was found</div>
            <div className="drawer-section-body">
              {decision.blocked_sources.length > 0 ? (
                <div className="feature-tags">
                  {decision.blocked_sources.map((source) => (
                    <span className="feature-tag feature-tag--danger" key={source}>{friendlySource(source)}</span>
                  ))}
                </div>
              ) : <p className="webpage-scan-empty">No specific location was reported.</p>}
            </div>
          </section>

          <section className="drawer-section">
            <div className="drawer-section-header">Details of what was detected</div>
            <div className="drawer-section-body">
              {decision.findings.length > 0 ? (
                <div className="webpage-scan-chunks">
                  {decision.findings.map((finding, index) => (
                    <FindingCard finding={finding} key={`${finding.source}-${index}`} />
                  ))}
                </div>
              ) : (
                <p className="webpage-scan-empty">
                  The scan flagged this page as unsafe, but did not return the specific matched text.
                </p>
              )}
            </div>
          </section>
        </div>
      </section>
    </>
  )
}
